[global]
archive-async=y
compress-type=zst
log-level-console=info
log-level-file=detail
log-path=/var/log/pgbackrest
lock-path=/tmp/pgbackrest
neutral-umask=y
process-max=2
repo1-path=/foah-rss
repo1-retention-archive-type=full
repo1-retention-full=4
repo1-retention-full-type=count
repo1-type=s3
spool-path=/var/spool/pgbackrest
start-fast=y

[foah_rss]
pg1-path=/var/lib/postgresql/18/docker
